version: "3.3"

services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
            - "--log.level=INFO"
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.file.filename=/dynamic.yaml"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true" # <== Enable TLS-ALPN-01 to generate and renew ACME certs
            - "--certificatesresolvers.mytlschallenge.acme.email=<your_email>" # <== Setting email for certs
            - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json" # <== Defining acme file to store cert information
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./letsencrypt:/letsencrypt"
            - "./dynamic.yaml:/dynamic.yaml"
        labels:
            - "traefik.enable=false"
            - "traefik.http.routers.api.rule=Host(`your_domain`)"
            - "traefik.http.routers.api.service=api@internal"

              #    code-server:
              #        image: ghcr.io/linuxserver/code-server
              #        container_name: code-server
              #        environment:
              #            - PUID=1000
              #            - PGID=1000
              #            - TZ=America/Sao_Paulo
              #            - PASSWORD= 
              #        labels:
              #            - "traefik.enable=true"
              #            - "traefik.http.routers.code.rule=Host(`your_domain`)"
              #            - "traefik.http.routers.code.entrypoints=web"
              #            - "traefik.http.routers.code.middlewares=redirect@file"
              #            - "traefik.http.routers.code-secured.rule=Host(`your_domain`)"
              #            - "traefik.http.routers.code-secured.entrypoints=websecure"
              #            - "traefik.http.routers.code-secured.tls.certresolver=mytlschallenge"
              #        volumes:
              #            - ./code/config:/config
              #        restart: unless-stopped
              #
    portainer:
        image: portainer/portainer-ce:2.0.0
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`your_domain`)"
            - "traefik.http.routers.portainer.entrypoints=web"
            - "traefik.http.routers.portainer.middlewares=redirect@file"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            - "traefik.http.routers.portainer-secured.rule=Host(`your_domain`)"
            - "traefik.http.routers.portainer-secured.entrypoints=websecure"
            - "traefik.http.routers.portainer-secured.tls.certresolver=mytlschallenge"

volumes:
    portainer_data:
